Periodic mesh in omega_h
SCOREC/omega_h pull request #10
Opened 2021-03-30 21:44 UTC by joshia5

2021-04-02 19:56 UTC, cwsmith commented
@joshia5 Will merging this cause any problems with non-periodic meshes?  Was there an issue with osh files not being compatible?

2021-04-15 16:56 UTC, joshia5 commented
@cwsmith as this pr stands now, i am expecting the merge to overwrite the mixed mesh sim2osh converter which is in scorec/master and create compatibility issues for mixed meshes because this work does not yet support mixed-periodic meshes. However any workflows based on sim2osh
mesh conversion that are using your branch https://github.com/SCOREC/omega_h/tree/cws/meshSimReader, should not be affected

2021-04-15 18:55 UTC, cwsmith commented
@joshia5 Thank you.  Is it possible to maintain support for simmetrix-to-osh conversion for all three (periodic, mixed, and mono-topology)?  Ideally, I'd like to merge everything (including https://github.com/SCOREC/omega_h/tree/cws/meshSimReader) into `master`.

2021-04-15 19:13 UTC, joshia5 commented
@cwsmith there are two ways to go on about it. first one is to make a robust utility which can handle all three types of
meshes. this will require a higher development time. second is to make individual utilities for all three (simplex, mixed and periodic, however the mixed and simplex converters can be grouped together).  from where the code is now, the second option should not be much difficult to implement.

2021-04-16 11:15 UTC, cwsmith commented
@joshia5 I think having a converter that supports simplex+mixed will cover 90% of our usage so having a separate converter that deals with periodic is OK.  Adding checks to each converter to ensure that the meshes provided by the user are of the correct type would make this strategy robust.

2021-06-28 14:02 UTC, cwsmith requested changes
Looks good. I submitted a small PR to your branch to fix a few small issues:
https://github.com/joshia5/omega_h/pull/2

2021-06-28 15:49 UTC, joshia5 commented on src/Omega_h_remotes.hpp
> +struct c_Remotes {
@cwsmith The  compressed remotes data structure a.k.a `c_Remotes` is used for storing matches

2021-06-28 15:57 UTC, joshia5 commented on src/Omega_h_matchMeshsim.cpp
> +          ++count_matches;
I think there might be some confusion. `count_matches` is number of matches for each 'self' entity. `++count_matches` seems ok to me.

2021-06-28 16:36 UTC, cwsmith commented on src/Omega_h_matchMeshsim.cpp
> +          ++count_matches;
I should have put this comment one line lower. I'm suggesting replacing:

```
          ++count_matches;
          ++count_matches;
```

with:

```
          count_matches+=2;
```

2021-06-28 16:37 UTC, cwsmith commented on src/Omega_h_matchMeshsim.cpp
> +          ++count_matches;
Yeah... I misread this as `count_matches++` twice.  Sorry about that.

2021-06-28 19:34 UTC, joshia5 commented on src/Omega_h_matchMeshsim.cpp
> +  mesh->set_periodic(1);
> I assume that if someone loads a non-periodic/matched mesh then the converter will fail?
Yes

2021-07-01 16:55 UTC, cwsmith approved these changes

2021-07-01 16:56 UTC, merged